-- ============================================================
-- DROP SCHEMA QUEQUE (sin tocar dbo.TablaMaestra)
-- ============================================================

-- Procedures
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Paises;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Provincia;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Alianzas;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Canal_Venta;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Medio_Pago;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Ciudades;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Agencias;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Aeropuerto;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Aerolineas;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Agentes;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Clientes;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Hospedajes;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Habitaciones;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Proveedores;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Excursiones;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Vuelos;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Solicitud_Cotizacion;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Solicitud_X_Ciudad;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Propuesta;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Ventas;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Reserva_Vuelo;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Reserva_Habitacion;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Reserva_Excursion;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Estado_Propuesta;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_AspectoValorado;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Encuestas;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_ValoracionEncuesta;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Propuesta_Vuelo;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Propuesta_Habitación;
DROP PROCEDURE IF EXISTS QUEQUE.Migrar_Venta_X_Propuesta;

-- Detalle / tablas hoja
DROP TABLE IF EXISTS QUEQUE.ValoracionEncuesta;
DROP TABLE IF EXISTS QUEQUE.Encuesta;

DROP TABLE IF EXISTS QUEQUE.Reserva_Excursion;
DROP TABLE IF EXISTS QUEQUE.Reserva_Habitacion;
DROP TABLE IF EXISTS QUEQUE.Reserva_Vuelo;
DROP TABLE IF EXISTS QUEQUE.Venta_X_Propuesta;
DROP TABLE IF EXISTS QUEQUE.Venta;

DROP TABLE IF EXISTS QUEQUE.Propuesta_Habitacion;
DROP TABLE IF EXISTS QUEQUE.Propuesta_Vuelo;
DROP TABLE IF EXISTS QUEQUE.Propuesta;
DROP TABLE IF EXISTS QUEQUE.Ciudad_x_Solicitud;
DROP TABLE IF EXISTS QUEQUE.SolicitudCotizacion;

DROP TABLE IF EXISTS QUEQUE.AspectoValorado;

-- Vuelos y hospedajes
DROP TABLE IF EXISTS QUEQUE.Vuelo;
DROP TABLE IF EXISTS QUEQUE.Excursion;
DROP TABLE IF EXISTS QUEQUE.Habitacion;
DROP TABLE IF EXISTS QUEQUE.Hospedaje;
DROP TABLE IF EXISTS QUEQUE.Aeropuerto;
DROP TABLE IF EXISTS QUEQUE.Aerolinea;

-- Personas
DROP TABLE IF EXISTS QUEQUE.Agente;
DROP TABLE IF EXISTS QUEQUE.Cliente;
DROP TABLE IF EXISTS QUEQUE.Agencia;
DROP TABLE IF EXISTS QUEQUE.Proveedor;

-- Lookups
DROP TABLE IF EXISTS QUEQUE.CanalVenta;
DROP TABLE IF EXISTS QUEQUE.MedioPago;
DROP TABLE IF EXISTS QUEQUE.EstadoPropuesta;
DROP TABLE IF EXISTS QUEQUE.Alianza;

-- Geografía
DROP TABLE IF EXISTS QUEQUE.Ciudad;
DROP TABLE IF EXISTS QUEQUE.Provincia;
DROP TABLE IF EXISTS QUEQUE.Pais;

-- Schema
DROP SCHEMA IF EXISTS QUEQUE;
GO